---

- hosts: all
  become: true
  pre_tasks:

# - name: install updates (Ubuntu)
#    tags: always
#    apt:
#      upgrade: dist
#      update_cache: yes
#    when: ansible_distribution == "Ubuntu"

#- hosts: ubuntu
#  become: true
#  roles:
#    - name: ubuntu

#  - name: install updates (CentOS)
#    tags: always
#    yum:
#      name: "*"
#      update_only: yes
#      update_cache: yes
#    when: ansible_distribution == "CentOS"

- hosts: centos
  become: true
  roles:
    - name: centos
